// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gofiber/fiber/v2"
	"github.com/kouhei-github/golang-ddd-boboilerplate/handler"
	"github.com/kouhei-github/golang-ddd-boboilerplate/repository"
	"github.com/kouhei-github/golang-ddd-boboilerplate/router"
	"github.com/kouhei-github/golang-ddd-boboilerplate/service"
	"gorm.io/gorm"
)

type Router interface {
	Register(c fiber.Router)
}

func NewRouter(db gorm.DB) Router {
	hellowWorld := repository.NewHelloWorldRepository(db)
	helloWorldService := service.NewHelloWorldService(hellowWorld)
	helloWorldHandler := handler.NewHelloWorldHandler(helloWorldService)
	routerRouter := router.NewRouter(helloWorldHandler)
	return routerRouter
}
