// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gofiber/fiber/v2"
	"github.com/kouhei-github/golang-ddd-boboilerplate/handlers"
	"github.com/kouhei-github/golang-ddd-boboilerplate/repositories"
	"github.com/kouhei-github/golang-ddd-boboilerplate/routers"
	"github.com/kouhei-github/golang-ddd-boboilerplate/services"
	"gorm.io/gorm"
)

type Router interface {
	Register(c fiber.Router)
}

func NewRouter(db gorm.DB) Router {
	hellowWorld := repositories.NewHelloWorldRepository(db)
	helloWorldService := services.NewHelloWorldService(hellowWorld)
	helloWorldHandler := handlers.NewHelloWorldHandler(helloWorldService)
	routerRouter := routers.NewRouter(helloWorldHandler)
	return routerRouter
}
