### POST request to signup
POST http://localhost:8080/api/v1/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1Test@test2"
}

### POST request to login
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1Test@test2"
}